const dictionary: Record<string, string> = {
  "Your browser couldn’t start the 3D arena. Enable hardware acceleration, then reload to try again.": "你的浏览器无法启动 3D 竞技场。请启用硬件加速，然后刷新重试。",
  "The arena could not be loaded. Check your connection and reload.": "无法加载竞技场。请检查网络连接后刷新。",
  "OBJECTIVE COMPLETE · +": "目标完成 · +",
  "WINDWARD": "迎风",
  "ESTABLISHING UPLINK": "正在建立上行链路",
  "TAKE A BREATHER.": "歇口气吧。",
  "WE’LL HOLD": "我们会为你",
  "YOUR PLACE.": "留好位置。",
  "The arena is paused. Your squad can wait.": "竞技场已暂停。队友们会等你。",
  "BACK IN THE FIGHT": "重返战斗",
  "SETTINGS": "设置",
  "CONTROLS": "操作说明",
  "FINISH PRACTICE": "结束练习",
  "LEAVE MATCH": "离开比赛",
  "TO RESUME": "继续游戏",
  "Match results": "比赛结果",
  "PRACTICE COMPLETE": "练习完成",
  "MATCH COMPLETE": "比赛结束",
  "YOU CAME. YOU FOUGHT. YOU CONQUERED.": "你来了。你战斗了。你征服了。",
  "A LITTLE SHARPER. A LITTLE STRONGER.": "更敏锐一点。更强大一点。",
  "THE RING HAD THE FINAL WORD.": "缩圈决定了最终结局。",
  "EVERY LEGEND STARTS SOMEWHERE.": "每个传奇都有起点。",
  "CHAMPION": "冠军",
  "READY FOR MORE.": "准备好再战一场。",
  "THE NEXT DROP AWAITS.": "下一次空降等着你。",
  "The wind station know your name.": "风站已记住你的名字。",
  "Take what you learned into the arena.": "把学到的本领带进竞技场。",
  "Regroup. Reload. Write a different ending.": "重整队伍。装填弹药。改写结局。",
  "ELIMINATIONS": "淘汰数",
  "DAMAGE DEALT": "造成伤害",
  "ASSISTS": "助攻数",
  "SURVIVED": "存活时间",
  "SQUAD PLACEMENT": "小队排名",
  "XP": "经验值",
  "CREDITS": "点数",
  "BACK TO LOBBY": "返回大厅",
  "RUN IT BACK": "再来一局",
  "Practice is its own reward.": "练习本身就是收获。",
  "Career progress saved on this device.": "生涯进度已保存在此设备上。",
  "CHOOSE YOUR DROP": "选择空降地点",
  "Play instantly in your browser. Squadmates and rivals are AI controlled.": "打开浏览器即可开战。队友和对手均由人工智能控制。",
  "MAKE YOURSELF AT HOME": "调到最顺手",
  "GAMEPLAY": "游戏设置",
  "Mouse sensitivity": "鼠标灵敏度",
  "Lower values give you finer aim control.": "数值越低，瞄准控制越精细。",
  "Invert vertical look": "反转垂直视角",
  "Reverse up and down mouse movement.": "反转鼠标上下移动的视角方向。",
  "AUDIO": "音频",
  "Game audio": "游戏音效",
  "Weapon sounds, abilities, and battle feedback.": "武器音效、技能音效与战斗反馈。",
  "Master volume": "主音量",
  "DISPLAY": "显示",
  "Graphics quality": "画质",
  "Choose Performance for lighter rendering.": "选择性能模式可减轻渲染负担。",
  "High quality": "高画质",
  "Performance": "性能",
  "Changes saved automatically": "更改已自动保存",
  "RESET DEFAULTS": "恢复默认设置",
  "GET YOUR BEARINGS": "熟悉战场",
  "Eliminate all three rival squads before the ring closes. Use cover, stay with your squad, and let your abilities turn the fight.": "在安全区完全收缩前，淘汰全部 3 支敌方小队。利用掩体，紧跟队友，用技能扭转战局。",
  "Shields regenerate after 8 seconds without damage. Collect supply cells around the arena for instant health and shields.": "连续 8 秒未受到伤害后，护盾会开始恢复。拾取竞技场中的补给电池可立即恢复生命值和护盾。",
  "Your ultimate charges over time and faster when you deal damage. Use Q often. It recharges.": "终极技能会随时间充能，造成伤害可加快充能。多用 Q，技能会冷却恢复。",
  "On touch screens, use the left joystick to move, drag the arena to look, and tap the action buttons to fight.": "使用触屏时，通过左侧摇杆移动，拖动竞技场画面调整视角，点击动作按钮进行战斗。",
  "GOT IT. LET’S GO.": "明白了。出发吧。",
  "GOOD COMPANY. BAD INTENTIONS.": "可靠的伙伴。凶狠的来意。",
  "You’re dropping with two AI squadmates. They follow your lead, engage nearby rivals, and have your back when things get loud.": "你将与两名智能队友一同空降。他们会跟随你的指挥，迎击附近的对手，在交火时为你提供支援。",
  "DRAFT.01": "新兵.01",
  "SQUAD LEADER": "小队队长",
  "You call the shots. Choose your route and your squad will follow.": "由你发号施令。选好路线，小队便会跟上。",
  "ANVIL": "铁砧",
  "DEFENDER · AI": "防御者 · 智能队友",
  "Steady under pressure. Anvil draws enemy fire and holds the frontline.": "临危不乱。铁砧负责吸引敌方火力，坚守前线。",
  "WINDLE": "温德尔",
  "RECON · AI": "侦察者 · 智能队友",
  "Your second set of eyes. Windle stays close and pressures exposed enemies.": "你的另一双眼睛。温德尔会紧随左右，压制暴露的敌人。",
  "Stay within 8 meters of your squad to keep their firepower close. Boren’s ultimate restores allied health.": "与队友保持在 8 米以内，便于获得火力支援。博伦的终极技能可恢复友军生命值。",
  "WELCOME TO THE WINDWARD": "欢迎来到迎风",
  "WIND STATIONS": "风站",
  "DIVISION": "赛区",
  "EST. 2187 / SECTOR 07": "建于 2187 / 07 区",
  "The edge of the map.": "地图的边缘。",
  "The start of your story.": "你的故事，由此开始。",
  "Anemone Basin used to be a mining outpost. Now its sun-bleached towers and abandoned freight yards host the fiercest fights in the wind station.": "银莲花盆地曾是一处采矿前哨。如今，烈日晒褪色的高塔和废弃货场，已成为风站最激烈的交战地。",
  "Choose a Competitor, gear up, and lead your squad through a three-minute battle. Nine rivals stand between you and the title. The ring won’t wait.": "选择一名参赛者，整装出发，带领小队投入一场三分钟的战斗。你与冠军头衔之间，还隔着九名对手。安全区可不会等你。",
  "SQUAD UP": "集结小队",
  "FIND YOUR EDGE": "找到优势",
  "TAKE THE TITLE": "夺取冠军",
  "An original browser arena inspired by the hero-shooter genre. No downloads, accounts, or real-money purchases. Your career and earned cosmetics stay on this device.": "一款受英雄射击游戏启发的原创浏览器竞技游戏。无需下载、注册账号或花费真钱。你的生涯进度和赢得的外观都保存在此设备上。",
  "RIDE YOUR OWN CURRENT": "乘着自己的风前行",
  "A LITTLE MORE TO FIGHT FOR": "多一个奋战的理由",
  "Earn credits through squad matches and objectives. Spend them on field finishes for your Competitors.": "通过小队比赛和目标赚取信用点，为你的参赛者购买战地涂装。",
  "CLAIMED": "已领取",
  "CLAIM REWARD": "领取奖励",
  "IN PROGRESS": "进行中",
  "A DIFFERENT KIND OF STATEMENT": "别样的个性宣言",
  "A fresh armor finish for all three Competitors.": "为全部三名参赛者换上全新护甲涂装。",
  "Purely cosmetic. Entirely yours.": "仅改变外观。完全属于你。",
  "YOUR BALANCE": "你的余额",
  "UNLOCK FOR": "解锁所需",
  "Earn more credits by completing matches and field objectives.": "完成比赛和战地目标，赚取更多信用点。",
  "UPLINK INTERRUPTED": "上行链路中断",
  "RELOAD ARENA": "重新加载竞技场",
  "SECTOR 07": "07 区",
  "ANEMONE STATION": "银莲花站",
  "Close tactical map": "关闭战术地图",
  "Tactical map with squad and enemy positions": "显示小队和敌人位置的战术地图",
  "YOU": "你",
  "SQUAD": "小队",
  "RIVALS": "对手",
  "RING": "安全区",
  "Open tactical map": "打开战术地图",
  "PRACTICE SESSION": "练习模式",
  "RING CLOSES IN": "安全圈缩小倒计时",
  "RING CLOSING": "安全圈正在缩小",
  "TARGETS": "靶标",
  "SQUADS LEFT": "剩余小队",
  "Pause game": "暂停游戏",
  "RELOADING": "正在装填",
  "GET BACK INSIDE THE RING": "快回到安全圈内",
  "AI": "电脑",
  "SHIELD CELL": "护盾电池",
  "ARC GRENADE": "电弧手雷",
  "Reload weapon": "装填武器",
  "RELOAD": "装填",
  "SPRINT": "冲刺",
  "JUMP": "跳跃",
  "SLIDE": "滑铲",
  "ELIMINATE EVERY RIVAL SQUAD": "消灭所有敌方小队",
  "FIRING RANGE": "射击场",
  "SQUAD ASSAULT": "小队突击",
  "GET A FEEL FOR YOUR FIREPOWER.": "感受你的火力。",
  "STAY TOGETHER. MAKE IT COUNT.": "紧跟队友。全力出击。",
  "WASD TO MOVE · MOUSE TO LOOK · LEFT CLICK TO FIRE": "WASD 移动 · 鼠标控制视角 · 左键开火",
  "Movement joystick": "移动摇杆",
  "Fire weapon": "武器开火",
  "Jump": "跳跃",
  "Tactical map": "战术地图",
  "Windward Relay home": "迎风接力首页",
  "WINDWARD RELAY": "迎风接力",
  "RIDE THE STATION WINDS": "乘风驰骋于风站",
  "Main navigation": "主导航",
  "LOADOUT": "装备配置",
  "COMPETITORS": "参赛者",
  "Earn credits by playing matches": "参加比赛赚取点数",
  "Mute sound": "静音",
  "Enable sound": "开启声音",
  "Open settings": "打开设置",
  "View your career": "查看生涯",
  "Choose a wind station competitor": "选择一位风站参赛者",
  "WIND": "迎",
  "WARD": "风",
  "STATION 0": "风站 0",
  "SEASON 01": "赛季 01",
  "A NEW WINDWARD": "全新的迎风之旅",
  "NO TWO COMPETITORS ARE THE SAME.": "每位参赛者都独一无二。",
  "RIDE YOUR": "驾驭",
  "OWN": "专属于你的",
  "CURRENT.": "气流。",
  "Find your edge. Trust your squad.": "找到你的优势。信任你的小队。",
  "Leave your mark on the wind station.": "在风站留下你的印记。",
  "Your next great story starts here": "你的下一段精彩故事，由此开始",
  "Change game mode": "更改游戏模式",
  "PRACTICE": "练习",
  "AI SQUADS": "电脑小队",
  "CHANGE": "更改",
  "READY UP": "准备就绪",
  "PREPARING ARENA": "正在准备竞技场",
  "YOUR SQUAD IS READY. ARE YOU?": "你的小队已就绪。你呢？",
  "YOUR RANGE. YOUR RULES.": "你的靶场。你的规则。",
  "FREE TO PLAY": "免费游玩",
  "CHOOSE COMPETITOR": "选择参赛者",
  "YOUR SQUAD": "你的小队",
  "Ready for deployment": "整装待发",
  "Holds the line": "坚守阵线",
  "Watches your six": "守护你的后方",
  "SQUAD DETAILS": "小队详情",
  "FIELD OBJECTIVES": "战地目标",
  "A little ambition goes a long way.": "一点雄心，也能走得很远。",
  "VIEW ALL OBJECTIVES": "查看所有目标",
  "FIELD NOTES / 001": "战地笔记 / 001",
  "NEW GROUND. NEW RULES.": "全新战场。全新规则。",
  "THIS IS YOUR WINDWARD.": "这是你的迎风之旅。",
  "GET TO KNOW THE WIND STATIONS": "了解风站",
  "THE WINDWARD DOESN’T MAKE COMPETITORS. YOU DO.": "成就参赛者的不是迎风之旅，而是你。",
  "MEET YOUR": "发现你的",
  "ADVANTAGE.": "制胜优势。",
  "Three different instincts. One shared mission.": "三种不同的本能。同一个使命。",
  "FIELD FINISH": "战地涂装",
  "Equip": "装备",
  "Unlock": "解锁",
  "EVERY DROP COUNTS.": "每次空降，都有意义。",
  "YOUR STORY.": "你的故事。",
  "STILL UNWRITTEN.": "尚待书写。",
  "Every match is another mark on the Windward Relay.": "每场比赛，都会在迎风接力中留下新的印记。",
  "WINDWARD RECRUIT": "迎风新兵",
  "LEVEL": "等级",
  "TOTAL XP": "总经验值",
  "THE NEXT CHAPTER": "下一篇章",
  "VICTORIES": "胜利场次",
  "MATCHES PLAYED": "已玩场次",
  "CLAIM": "领取",
  "LOCAL REGION": "本地区域",
  "SOLO + AI SQUAD": "单人 + 电脑小队",
  "TRAINING GROUND": "训练场",
  "BUILD 01.04": "版本 01.04",
  "HOW TO PLAY": "玩法说明",
  "FIELD GUIDE": "野外手册",
  "FULLSCREEN": "全屏",
  "THE RIGHT TOOL. YOUR RULES.": "趁手的武器。你的规则。",
  "BUILT FOR": "专为",
  "THE MOMENT.": "此刻而生。",
  "Find the weapon that feels like second nature.": "找到那把让你得心应手的武器。",
  "SPECIFICATIONS": "规格参数",
  "FIELD NOTES": "战地笔记",
  "DAMAGE": "伤害",
  "FIRE RATE": "射速",
  "RANGE": "射程",
  "PRECISION": "精准度",
  "MAGAZINE": "弹匣容量",
  "RELOAD TIME": "装填时间",
  "BASE DAMAGE": "基础伤害",
  "Fire short bursts at distant enemies. Aim down sights for tighter accuracy, and reload behind cover before pushing.": "以短点射攻击远处的敌人。开镜瞄准可提高精度，推进前先在掩体后换弹。",
  "Close the distance using Tavi’s dash. Keep your crosshair on the center of the target to land all eight pellets.": "利用塔薇的突进拉近距离。将准星保持在目标中心，让全部八枚弹丸命中。",
  "Hold a clear sightline and aim for the helmet. A headshot deals 65% more damage. Reposition between shots.": "保持视线畅通，瞄准头盔。爆头额外造成65%伤害。每次射击后都要转移位置。",
  "RMB": "RMB",
  "AIM": "瞄准",
  "EQUIPPED FOR NEXT DROP": "已装备，下次空投生效",
  "SELECTED": "已选择",
  "SELECT MODE": "选择模式",
  "Close dialog": "关闭对话框",
  "TAVI": "塔薇",
  "SKIRMISHER": "突击手",
  "Always one step ahead.": "永远快人一步。",
  "“Catch me if you can.”": "“有本事就追上我。”",
  "A wind-station courier with five folding sail panels. Tavi rides sudden crosswinds between the instrument towers.": "风站信使，配备五面折叠风帆。塔薇乘着突如其来的侧风，穿梭于仪器塔之间。",
  "SAIL SURGE": "风帆突进",
  "Surge in your movement direction. Become invulnerable for 1.2 seconds.": "向移动方向突进。获得1.2秒无敌。",
  "FULL SAIL": "全帆疾行",
  "For 10 seconds, move faster and fire without consuming ammunition.": "持续10秒，提高移动速度，射击不消耗弹药。",
  "BOREN": "博伦",
  "DEFENDER": "防御者",
  "Be the last one standing.": "坚持到最后。",
  "“This is as far as you go.”": "“你只能走到这里了。”",
  "A pressure-house keeper with a quilted storm coat and a broad instrument pack. Boren gives the relay crew shelter in the gusts.": "气压房守护者，身披绗缝防风大衣，背着宽大的仪器包。博伦为接力小队遮挡狂风。",
  "PRESSURE COAT": "气压护衣",
  "Restore 45 shield and reduce incoming damage by 65% for 5 seconds.": "恢复45点护盾，受到的伤害降低65%，持续5秒。",
  "STORM SHELTER": "风暴庇护",
  "Restore your squad’s health and shields. Gain 10 seconds of damage resistance.": "恢复小队的生命值和护盾。获得10秒伤害抗性。",
  "NIMA": "妮玛",
  "RECON": "侦察兵",
  "They can run. You can see.": "任敌人逃窜，也逃不出你的视线。",
  "“I already know your next move.”": "“我早已看穿你的下一步。”",
  "An anemometer builder with split goggles and a mast of copper sensors. Nima reads every wake across Anemone Station.": "风速仪制造师，戴着分体护目镜，背着装满铜制传感器的桅杆。妮玛能读懂风花站内的每一道尾流。",
  "WIND SOUNDING": "探风",
  "Reveal every opponent for 8 seconds and disrupt nearby enemies.": "显示所有对手的位置，持续8秒，并干扰附近的敌人。",
  "GUST CASCADE": "疾风连涌",
  "Release an energy shockwave that deals 70 damage to enemies within 32 meters.": "释放能量冲击波，对32米内的敌人造成70点伤害。",
  "VANE-30": "风向标-30",
  "ASSAULT RIFLE": "突击步枪",
  "Steady hands. Relentless pressure. A versatile automatic rifle built for any engagement.": "稳住双手，持续压制。这把全能自动步枪适合各种交战场景。",
  "BELLOWS-8": "风箱-8",
  "SHOTGUN": "霰弹枪",
  "Get close. Make it count. Eight heavy pellets deliver a devastating answer at short range.": "贴近目标，一击制胜。八枚重型弹丸在近距离给予毁灭性的回击。",
  "ALIDADE-10": "照准仪-10",
  "MARKSMAN": "精确射手步枪",
  "Find your angle and own it. High-impact precision for the patient hunter.": "找准角度，掌控战局。为耐心的猎手提供威力强大的精准打击。",
  "TRIOS": "三人小队",
  "You + 2 AI allies · 3 rival squads": "你 + 2名AI队友 · 3支敌方小队",
  "Nine rivals. One closing ring. Lead your squad to the last stand.": "九名对手，一个不断收缩的安全区。带领小队奋战到最后。",
  "SOLO": "单人",
  "Practice · Unlimited respawns": "练习 · 无限重生",
  "Learn your Competitor, test every weapon, and find your rhythm.": "熟悉你的选手，试用每一把武器，找到自己的节奏。",
  "FREE ROAM": "自由探索",
  "LEEWIND PRACTICE": "背风训练场",
  "FIELD ISSUE": "外勤制式",
  "AUTUMN SAIL": "秋日风帆",
  "SIGNAL RED": "信号红",
  "Boots on the ground": "踏上战场",
  "Complete a squad match": "完成一场小队比赛",
  "Make every shot count": "弹无虚发",
  "Deal 1,000 damage": "造成1,000点伤害",
  "A competitor in the making": "崭露头角",
  "Win a squad match": "赢得一场小队比赛",
  "Move": "移动",
  "MOUSE": "鼠标",
  "Look around": "环顾四周",
  "LEFT CLICK": "鼠标左键",
  "RIGHT CLICK": "鼠标右键",
  "Aim down sights": "开镜瞄准",
  "Sprint": "疾跑",
  "Slide": "滑铲",
  "Reload": "换弹",
  "Tactical ability": "战术技能",
  "Ultimate ability": "终极技能",
  "Shield cell": "护盾电池",
  "Arc grenade": "电弧手雷",
  "TAB / M": "TAB / M",
  "ESC / P": "ESC / P",
  "Pause": "暂停",
  "DUNE.RUNNER": "沙丘.行者",
  "CINDER": "余烬",
  "STATIC": "静电",
  "REDLINE": "红线",
  "GHOST-07": "幽灵-07",
  "WICKER.EXE": "柳条.EXE",
  "COPPER": "赤铜",
  "VANDAL": "破坏者",
  "NOMAD": "游牧者",
  "Interactive 3D Windward Relay arena": "迎风接力交互式3D竞技场",
  "The 3D renderer was interrupted. Reload the arena to reconnect.": "3D渲染器已中断。请重新加载竞技场以恢复连接。",
  "FIRING RANGE · MAKE YOURSELF AT HOME": "靶场 · 尽情练习",
  "ELIMINATE THE RIVAL SQUADS": "淘汰敌方小队",
  "FIRING RANGE · 5 TARGETS ONLINE": "靶场 · 5个靶标已启用",
  "ANVIL + WINDLE joined your squad": "铁砧 + 温德尔加入了你的小队",
  "SUPPLY COLLECTED · +35 HEALTH & SHIELD": "已拾取补给 · +35生命值与护盾",
  "TACTICAL RECHARGING · ": "战术技能冷却中 · ",
  "ULTIMATE CHARGING · ": "终极技能充能中 · ",
  "SHIELD CELL RECHARGING · ": "护盾电池冷却中 · ",
  "HEALTH & SHIELDS ALREADY FULL": "生命值与护盾均已满",
  "SHIELD CELL · +45 SHIELD / +20 HEALTH": "护盾电池 · +45护盾 / +20生命值",
  "ARC GRENADE RECHARGING · ": "电弧手雷冷却中 · ",
  "ARC GRENADE DEPLOYED": "电弧手雷已投出",
  "ELIMINATED ": "已淘汰 ",
  "YOU  →  ": "你  →  ",
  "SQUAD  →  ": "小队  →  ",
  " was eliminated": " 已被淘汰",
  "WIND STATIONS DIVISION": "风站赛区",
  "DUSTFALL": "落尘",
  "BASIN  //  SECTOR 07": "盆地  //  07区",
  "LET’S RECONNECT.": "重新连接吧。",
  "The arena ran into an unexpected problem. Your saved career is safe.": "竞技场遇到了意外问题。你已保存的生涯进度不受影响。",
  "RELOAD WINDWARD": "重新加载迎风接力",
  "lobby": "大厅",
  "play": "开始游戏",
  "squads": "小队",
  "sandstorm": "沙尘暴",
  "skin": "皮肤",
  " UNLOCKED & EQUIPPED": " 已解锁 & 已装备",
  "app ": "应用 ",
  "mode": "模式",
  "about": "关于",
  "challenges": "挑战",
  "ended": "已结束",
  "paused": "已暂停",
  "dialog": "对话框",
  "fill": "填充",
  "training": "训练",
  "keycap": "键帽",
  "results-panel ": "results-panel ",
  "victory": "胜利",
  "thin": "细",
  "eyebrow": "眉题",
  "timeout": "超时",
  "placement": "排名",
  "checkbox": "复选框",
  "high": "高",
  "low": "低",
  "toast": "提示消息",
  "status": "状态",
  "tactical-map ": "tactical-map ",
  ") rotate(": ") rotate(",
  "middle": "中",
  "action-key ": "action-key ",
  "cooling": "冷却中",
  "hud ": "平视显示 ",
  "aiming": "瞄准中",
  "damage-vignette ": "damage-vignette ",
  "visible": "可见",
  "compass": "罗盘",
  "tick": "刻度",
  "friendly": "友方",
  "entity-label ": "entity-label ",
  "ally": "盟友",
  "enemy": "敌人",
  "crosshair ": "准星 ",
  "hit": "命中",
  "heal": "治疗",
  "tactical": "战术技能",
  "ultimate": "终极技能",
  "grenade": "手榴弹",
  "ammo-counter ": "ammo-counter ",
  "full": "已满",
  "countdown": "倒计时",
  "application": "应用程序",
  "regular": "常规",
  "carbine": "卡宾枪",
  "longshot": "远射手",
  "breacher": "破阵者",
  "portrait ": "头像 ",
  " portrait": " 头像",
  "portrait portrait-loading ": "portrait portrait-loading ",
  "lobby-shell view-": "lobby-shell view-",
  "topbar": "顶部栏",
  "brand": "品牌",
  "legends": "传奇",
  "armory": "军械库",
  "career": "生涯",
  "active": "当前",
  "page": "页面",
  "duotone": "双色调",
  "competitor-select ": "competitor-select ",
  "objective-icon ": "objective-icon ",
  "done": "完成",
  "reward-button ": "reward-button ",
  "claimable": "可领取",
  "version": "版本",
  "specs": "规格",
  "tips": "提示",
  "weapon-select ": "weapon-select ",
  "mode-option ": "mode-option ",
  "modal-panel ": "modal-panel ",
  "suspended": "已挂起",
  "sine": "正弦波",
  "lowpass": "低通",
  "shot": "射击",
  "sawtooth": "锯齿波",
  "heavy": "重型",
  "triangle": "三角波",
  "kill": "击杀",
  "square": "方波",
  "ability": "技能",
  "shield": "护盾",
  "hurt": "受伤",
  "start": "开始",
  "win": "获胜",
  "step": "脚步",
  "carbon": "碳",
  "signal": "信号",
  "matches": "对局",
  "sharpshooter": "神射手",
  "wins": "胜场",
  "qa": "质量保证",
  "tabindex": "tabindex",
  "rival": "对手",
  "playing": "游戏中",
  "map": "地图",
  "pointerlockchange": "pointerlockchange",
  "pointerlockerror": "pointerlockerror",
  "contextmenu": "contextmenu",
  "touchcancel": "touchcancel",
  "webglcontextlost": "webglcontextlost",
  "tracer": "曳光",
  "burst": "爆发",
  "sphere-": "球体-",
  "cylinder-": "圆柱体-",
  "position": "位置",
  "object": "对象",
  "kills": "击杀数",
  "uv": "uv",
  "root": "根节点",
  "ESC": "ESC",
  "THE WIND STATIONS ARE OPEN": "风之驿站现已开放",
  " recharging": " 充能中",
  "SHIFT": "SHIFT",
  "SPACE": "空格",
  "FPS": "帧率",
  "/ 600 XP": "/ 600 经验值",
  "/ 3 COMPLETE": "/ 3 已完成",
  "OBJECTIVE COMPLETE": "目标完成",
  "EST. 2187": "建于 2187",
  "WASD TO MOVE": "WASD 移动",
  "MOUSE TO LOOK": "鼠标控制视角",
  "LEFT CLICK TO FIRE": "左键开火",
  "You + 2 AI allies": "你 + 2名AI队友",
  "3 rival squads": "3支敌方小队",
  "Practice": "练习",
  "Unlimited respawns": "无限重生",
  "5 TARGETS ONLINE": "5个靶标已启用",
  "SUPPLY COLLECTED": "已拾取补给",
  "+35 HEALTH & SHIELD": "+35生命值与护盾",
  "TACTICAL RECHARGING": "战术技能冷却中",
  "ULTIMATE CHARGING": "终极技能充能中",
  "SHIELD CELL RECHARGING": "护盾电池冷却中",
  "+45 SHIELD / +20 HEALTH": "+45护盾 / +20生命值",
  "SHIELD CELL · +45 SHIELD": "护盾电池 · +45护盾",
  "+20 HEALTH": "+20生命值",
  "ARC GRENADE RECHARGING": "电弧手雷冷却中",
  "Cinderhorn Atlas": "烬角图志",
  "CINDERHORN": "烬角",
  "ATLAS": "图志",
  "Prism Keep": "棱光堡垒",
  "Copperline Breach": "铜线突围",
  "Afterhours Freight": "午夜货运",
  "Windward Relay": "迎风接力",
  "Velvet Circuit": "绒光回路",
  "The Ember Vow": "余烬之誓",
  "Scraplight Run": "拾光疾行",
  "Foldlight Duet": "折光二重奏",
  "Asterbridge Tales": "星桥物语",
  "The Lantern Compact": "灯火之约",
  "Mothglass Ascent": "蛾镜攀升",
  "Quiet Meridian": "寂静子午线",
  "Small Hours Studio": "小小时光",
  "Ropeflower": "绳花之旅",
  "Hoop Almanac": "篮场纪事",
  "Nimbus Salvagers": "云海拾荒者",
  "Switchboard Social": "接线台故事",
  "Inkroad Courier": "墨路信使",
  "Hearthwind Pact": "炉风盟约",
  "Paper Crane Crossing": "纸鹤渡",
  "Topaz Reliquary": "黄玉秘藏",
  "Porcelain Afterglow": "瓷光余晖",
  "Tramline Stories": "电车街故事",
  "Clockwork Orchard": "发条果园",
  "Bronze Rain Pilgrim": "铜雨行者",
  "Health": "生命值",
  "HP": "生命",
  "Stamina": "体力",
  "Energy": "能量",
  "Score": "得分",
  "Level": "等级",
  "Settings": "设置",
  "Continue": "继续",
  "Start": "开始",
  "Resume": "继续",
  "Restart": "重新开始",
  "Back": "返回",
  "Close": "关闭",
  "Cancel": "取消",
  "Confirm": "确认",
  "Loading": "加载中",
  "Loading…": "加载中…",
  "New Game": "开始游戏",
  "Game Over": "游戏结束",
  "Victory": "胜利",
  "Defeat": "失败",
  "Select": "选择",
  "Selected": "已选择",
  "Locked": "未解锁",
  "Unlocked": "已解锁",
  "Ready": "就绪",
  "Online": "在线",
  "Offline": "离线",
  "Connecting": "连接中",
  "Yes": "是",
  "No": "否",
  "On": "开启",
  "Off": "关闭",
  "Easy": "简单",
  "Normal": "普通",
  "Hard": "困难",
  "Mouse": "鼠标",
  "Left click": "鼠标左键",
  "Right click": "鼠标右键",
  "Space": "空格",
  "Escape": "Esc",
  "Credits": "点数",
  "Controls": "操作说明",
  "Help": "帮助",
  "Tutorial": "教程",
  "Inventory": "背包",
  "Ranged": "远程",
  "Melee": "近战",
  "Carry": "核心",
  "Support": "辅助",
  "Durable": "坚韧",
  "Map": "地图",
  "Career": "生涯",
  "Play": "开始游戏",
  "Loadout": "装备配置",
  "NPC": "角色",
  "Damage": "伤害",
  "Armor": "护甲",
  "Speed": "速度",
  "Attack": "攻击",
  "Defense": "防御",
  "Dodge": "闪避",
  "Mission": "任务",
  "Quest": "任务",
  "Objective": "目标",
  "Reward": "奖励",
  "Rewards": "奖励",
  "Exit": "退出",
  "Player": "玩家",
  "You": "你",
  "Enemy": "敌人",
  "Round": "回合",
  "Time": "时间",
  "Best": "最佳",
  "Connected": "已连接",
  "Disconnected": "已断开",
  "Room": "房间",
  "Create room": "创建房间",
  "Join room": "加入房间",
  "Volume": "音量",
  "Music": "音乐",
  "Sound": "音效",
  "Muted": "已静音",
  "Fullscreen": "全屏",
  "織工": "织工",
  "区 07": "07 区",
  "織 波": "织 潮",
  "ラーメン": "拉面",
  "夜市場": "夜市",
  "織路": "织路",
  "武器": "武器",
  "万事屋": "万事屋",
  "溺れる": "深水",
  "木漏れ日の谷": "林光谷",
  "静寂": "静谧",
  "風": "风"
};
const normalize = (value: string): string => value.replace(/\s+/g, ' ').trim().toLowerCase();
const exact = new Map(Object.entries(dictionary).map(([key, value]) => [normalize(key), value.trim()]));
const escapeRegExp = (value: string): string => value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const phrases = Array.from(exact.keys()).filter(key => /[a-z\u3040-\u30ff\u3400-\u9fff]/i.test(key) && key.length > 1).sort((a,b) => b.length-a.length);
const matcher = new RegExp(`(?<![a-z])(?:${phrases.map(escapeRegExp).join('|')})(?![a-z])`, 'gi');
const cache = new Map<string,string>();

export function translate(text: string): string {
  if (!text || !/[a-z\u3040-\u30ff\u3400-\u9fff]/i.test(text)) return text;
  const cached = cache.get(text); if (cached !== undefined) return cached;
  const key = normalize(text);
  const translated = exact.get(key);
  const value = translated !== undefined
    ? (text.match(/^\s*/)?.[0] || '') + translated + (text.match(/\s*$/)?.[0] || '')
    : text.replace(matcher, part => exact.get(normalize(part)) || part);
  if (cache.size > 10000) cache.clear();
  cache.set(text,value); return value;
}

